const clientes = [
  // 🟢 WALMART (ya lo tenías)
  {
    id: "walmart",
    nombre: "Walmart de México",
    meta: "Retail · Última Milla · 150 Unidades",
    nivel: "ALTO",
    tipo: "danger",
    otif: "82%",
    puntual: "75%",
    nps: "4/10",
    quejas: "18",
    tendencia: "↓ Crítico: Demoras en CEDIS",
    since: "2020",
    manager: "Luis Torres",

    services: [
      {
        name: "Rutas Centro CDMX",
        desc: "Distribución a tiendas urbanas con alta congestión.",
        area: "Transporte",
        expected: "01-Dic",
        real: "03-Dic",
        realClass: "severity-high",
        sl: "72%",
        slClass: "severity-high text-center",
        nps: "3/10",
        npsClass: "severity-high text-center",
      },
      {
        name: "Entrega CEDIS Norte",
        desc: "Abastecimiento a centros de distribución regionales.",
        area: "Transporte",
        expected: "02-Dic",
        real: "04-Dic",
        realClass: "severity-high",
        sl: "78%",
        slClass: "severity-high text-center",
        nps: "4/10",
        npsClass: "severity-high text-center",
      },
      {
        name: "Control Inventario",
        desc: "Validación de stock previo a embarque.",
        area: "Almacén",
        expected: "01-Dic",
        real: "02-Dic",
        realClass: "severity-mid",
        sl: "85%",
        slClass: "severity-mid text-center",
        nps: "5/10",
        npsClass: "severity-mid text-center",
      },
      {
        name: "Planeación Rutas",
        desc: "Asignación de ventanas y rutas.",
        area: "Coordinación",
        expected: "01-Dic",
        real: "03-Dic",
        realClass: "severity-high",
        sl: "70%",
        slClass: "severity-high text-center",
        nps: "3/10",
        npsClass: "severity-high text-center",
      },
      {
        name: "Atención Incidencias",
        desc: "Gestión de reclamos de tienda.",
        area: "Atención",
        expected: "01-Dic",
        real: "02-Dic",
        realClass: "severity-high",
        sl: "78%",
        slClass: "severity-mid text-center",
        nps: "4/10",
        npsClass: "severity-high text-center",
      },
    ],

    complaints: [
      {
        title: "Retrasos en CDMX",
        desc: "Demoras constantes en rutas urbanas.",
        area: "Transporte",
        date: "12 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Saturación CEDIS",
        desc: "Recepción excedida en ventanas.",
        area: "Transporte",
        date: "11 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Faltantes pedidos",
        desc: "Diferencias en surtido.",
        area: "Almacén",
        date: "10 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Errores picking",
        desc: "Errores en preparación.",
        area: "Almacén",
        date: "09 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "EN PROGRESO",
        statusClass: "badge--warning-light",
      },
      {
        title: "Planeación deficiente",
        desc: "Asignación tardía de rutas.",
        area: "Coordinación",
        date: "08 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Cambios última hora",
        desc: "Reprogramaciones frecuentes.",
        area: "Coordinación",
        date: "07 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Respuesta lenta",
        desc: "Atención tardía a incidencias.",
        area: "Atención",
        date: "06 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Falta visibilidad",
        desc: "Poca trazabilidad en pedidos.",
        area: "Tecnología",
        date: "05 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Unidades insuficientes",
        desc: "Falta de flota disponible.",
        area: "Transporte",
        date: "04 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Demoras descarga",
        desc: "Retrasos en recepción.",
        area: "Transporte",
        date: "03 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Inventario incorrecto",
        desc: "Descuadres frecuentes.",
        area: "Almacén",
        date: "02 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Errores SKU",
        desc: "Productos mal etiquetados.",
        area: "Almacén",
        date: "01 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Falta coordinación",
        desc: "Desalineación entre áreas.",
        area: "Coordinación",
        date: "30 Nov 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Ventanas incumplidas",
        desc: "Entregas fuera de horario.",
        area: "Coordinación",
        date: "29 Nov 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Escalaciones sin cierre",
        desc: "Casos abiertos sin resolución.",
        area: "Atención",
        date: "28 Nov 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Comunicación deficiente",
        desc: "Falta de seguimiento claro.",
        area: "Atención",
        date: "27 Nov 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Incumplimiento SLA",
        desc: "Servicios fuera de estándar.",
        area: "Transporte",
        date: "26 Nov 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Retrasos recurrentes",
        desc: "Problema estructural.",
        area: "Transporte",
        date: "25 Nov 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
    ],
    semaforo: "red",
    kpiStatus: {
      otif: "danger",
      puntual: "danger",
      nps: "danger",
      quejas: "danger"
    },
    diagnostico: {
      summary: "<p>Este cliente presenta un escenario de <span class=\"hl-danger\">alta criticidad operativa</span>: el OTIF ha colapsado al 82% y la puntualidad se encuentra en un alarmante 75%, afectando directamente las ventanas de entrega en tiendas retail.</p> <p>El volumen de <span class=\"hl-danger\">18 quejas activas</span> y la tendencia <span class=\"hl-warning\">crítica por demoras en CEDIS</span> indican un alto riesgo de penalizaciones económicas severas y pérdida inmediata de unidades asignadas si no se destraba el flujo logístico hoy mismo.</p>"
    },  
    keyFindings: [
      "Caída drástica de puntualidad (75%) originada por severos cuellos de botella y demoras de más de 4 horas en la carga dentro del CEDIS.",
      "18 quejas HIGH activas relacionadas con mercancía rechazada en tienda por llegar fuera de ventana de recibo.",
      "NPS en zona de detracción (4/10), reflejando una profunda insatisfacción del cliente con la visibilidad y respuesta de nuestra torre de control."
    ],

    actions: [
      {
        priority: "URGENTE",
        text: "Instalar \"War Room\" virtual inmediato con gerencia de CEDIS Walmart para destrabar unidades retenidas en rampa."
      },
      {
        priority: "URGENTE",
        text: "Asignar supervisor de guardia dedicado (Implant) físicamente en el CEDIS para agilizar procesos de carga y despacho."
      },
      {
        priority: "CORTO PLAZO",
        text: "Plan de choque para la resolución de las 18 quejas activas y conciliación de penalizaciones por entregas tardías (OTIF)."
      },
      {
        priority: "CORTO PLAZO",
        text: "Revisión exhaustiva de la disponibilidad mecánica de las 150 unidades asignadas a la cuenta Última Milla."
      },
      {
        priority: "PREVENTIVO",
        text: "Implementar célula en Torre de Control exclusiva para monitoreo GPS proactivo y notificación anticipada de retrasos en retail."
      },
      {
        priority: "PREVENTIVO",
        text: "Establecer comité semanal de KPIs con el cliente para recuperar confianza operativa y revisar SLA de ventanas de entrega."
      }
    ],
  },

  // 🔴 GM
  {
    id: "gm",
    nombre: "General Motors",
    meta: "Automotriz · Egoba",
    nivel: "ALTO",
    tipo: "danger",
    otif: "90%",
    puntual: "88%",
    nps: "7/10",
    quejas: "5",
    tendencia: "↓ Falta operadores",
    diagnostico: "diagnostico-General-Motors.html",
    since: "2019",
    manager: "Carlos Méndez",

    services: [
      {
        name: "Transporte Planta",
        desc: "Entrega de autopartes just-in-time.",
        area: "Transporte",
        expected: "01-Dic",
        real: "02-Dic",
        realClass: "severity-mid",
        sl: "88%",
        slClass: "severity-mid text-center",
        nps: "7/10",
        npsClass: "severity-mid text-center",
      },
      {
        name: "Distribución Regional",
        desc: "Entrega a distribuidores.",
        area: "Transporte",
        expected: "02-Dic",
        real: "02-Dic",
        realClass: "severity-low",
        sl: "91%",
        slClass: "severity-low text-center",
        nps: "7/10",
        npsClass: "severity-mid text-center",
      },
    ],

    complaints: [
      {
        title: "Falta de operadores",
        desc: "Escasez de choferes certificados en planta.",
        area: "Transporte",
        date: "10 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Retrasos en entregas JIT",
        desc: "Afectación a líneas de producción.",
        area: "Transporte",
        date: "09 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Capacidad limitada",
        desc: "Falta de unidades en horas pico.",
        area: "Transporte",
        date: "08 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Desalineación producción-logística",
        desc: "Fallas en sincronización de embarques.",
        area: "Coordinación",
        date: "07 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "EN PROGRESO",
        statusClass: "badge--warning-light",
      },
      {
        title: "Incidencias sin seguimiento",
        desc: "Casos abiertos sin cierre oportuno.",
        area: "Atención",
        date: "06 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
    ],
  },

  // 🟡 AMAZON
  {
    id: "amazon",
    nombre: "Amazon México",
    meta: "E-commerce · Redpack",
    nivel: "MEDIO",
    tipo: "warning",
    otif: "92%",
    puntual: "91%",
    nps: "6/10",
    quejas: "3",
    tendencia: "↓ Alta demanda",
    diagnostico: "diagnostico",
    since: "2021",
    manager: "Fernanda Ruiz",

    services: [
      {
        name: "Última Milla",
        desc: "Entrega a cliente final en zonas urbanas.",
        area: "Transporte",
        expected: "01-Dic",
        real: "02-Dic",
        realClass: "severity-mid",
        sl: "90%",
        slClass: "severity-mid text-center",
        nps: "6/10",
        npsClass: "severity-mid text-center",
      },
      {
        name: "Fulfillment",
        desc: "Preparación de pedidos en FC.",
        area: "Almacén",
        expected: "01-Dic",
        real: "02-Dic",
        realClass: "severity-mid",
        sl: "92%",
        slClass: "severity-mid text-center",
        nps: "6/10",
        npsClass: "severity-mid text-center",
      },
    ],

    complaints: [
      {
        title: "Saturación última milla",
        desc: "Alta demanda en zonas urbanas.",
        area: "Transporte",
        date: "12 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Retrasos en entregas",
        desc: "Volumen superior a capacidad.",
        area: "Transporte",
        date: "11 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Falta de repartidores",
        desc: "Cobertura insuficiente.",
        area: "Transporte",
        date: "10 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Errores en picking",
        desc: "Productos incorrectos enviados.",
        area: "Almacén",
        date: "09 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "EN PROGRESO",
        statusClass: "badge--warning-light",
      },
      {
        title: "Demoras en preparación",
        desc: "Retraso en centros fulfillment.",
        area: "Almacén",
        date: "08 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Inventario desactualizado",
        desc: "Stock no sincronizado.",
        area: "Almacén",
        date: "07 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Forecast inexacto",
        desc: "Planeación de demanda incorrecta.",
        area: "Coordinación",
        date: "06 Dic 2025",
        severity: "ALTO",
        severityClass: "badge--danger-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Reprogramaciones frecuentes",
        desc: "Cambios en rutas.",
        area: "Coordinación",
        date: "05 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Falta visibilidad pedidos",
        desc: "Tracking limitado.",
        area: "Tecnología",
        date: "04 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Errores tracking",
        desc: "Datos incorrectos en sistema.",
        area: "Tecnología",
        date: "03 Dic 2025",
        severity: "BAJO",
        severityClass: "badge--success-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Soporte lento",
        desc: "Tiempos largos de respuesta.",
        area: "Atención",
        date: "02 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Escalaciones abiertas",
        desc: "Casos sin resolución.",
        area: "Atención",
        date: "01 Dic 2025",
        severity: "MEDIO",
        severityClass: "badge--warning-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
    ],
  },

  {
    id: "heineken",
    nombre: "Heineken México",
    meta: "Consumo · Distribución",
    nivel: "BAJO",
    tipo: "warning",
    otif: "91%",
    puntual: "93%",
    nps: "7/10",
    quejas: "4",
    tendencia: "↓ Estacionalidad",
    diagnostico: "diagnostico-Heineken.html",
    since: "2020",
    manager: "Roberto Díaz",

    services: [
      {
        name: "Distribución Nacional",
        desc: "Entrega a centros de consumo.",
        area: "Transporte",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "98%",
        slClass: "severity-low text-center",
        nps: "9/10",
        npsClass: "severity-low text-center",
      },
    ],

    complaints: [
      {
        title: "Ajuste estacional",
        desc: "Variación en demanda por temporada.",
        area: "Coordinación",
        date: "10 Dic 2025",
        severity: "BAJO",
        severityClass: "badge--success-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
    ],
  },

  // 🟢 MERCADO LIBRE
  {
    id: "meli",
    nombre: "Mercado Libre",
    meta: "E-commerce · 3PL",
    nivel: "BAJO",
    tipo: "success",
    otif: "96%",
    puntual: "95%",
    nps: "8/10",
    quejas: "3",
    tendencia: "↑ Nuevas rutas",
    diagnostico: "diagnostico-Mercado-Libre.html",
    since: "2021",
    manager: "Sofía Navarro",

    services: [
      {
        name: "Última Milla Express",
        desc: "Entrega rápida urbana.",
        area: "Transporte",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "96%",
        slClass: "severity-low text-center",
        nps: "8/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Fulfillment",
        desc: "Preparación pedidos.",
        area: "Almacén",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "95%",
        slClass: "severity-low text-center",
        nps: "8/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Planeación Capacidad",
        desc: "Coordinación demanda.",
        area: "Coordinación",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "96%",
        slClass: "severity-low text-center",
        nps: "8/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Tracking Envíos",
        desc: "Monitoreo en tiempo real.",
        area: "Tecnología",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "97%",
        slClass: "severity-low text-center",
        nps: "8/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Soporte Seller",
        desc: "Atención vendedores.",
        area: "Atención",
        expected: "01-Dic",
        real: "02-Dic",
        realClass: "severity-mid",
        sl: "94%",
        slClass: "severity-mid text-center",
        nps: "8/10",
        npsClass: "severity-low text-center",
      },
    ],

    complaints: [
      {
        title: "Ajuste rutas nuevas",
        desc: "Optimización de rutas en expansión.",
        area: "Transporte",
        date: "10 Dic 2025",
        severity: "BAJO",
        severityClass: "badge--success-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Configuración tracking",
        desc: "Errores menores en monitoreo.",
        area: "Tecnología",
        date: "09 Dic 2025",
        severity: "BAJO",
        severityClass: "badge--success-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
      {
        title: "Consulta de sellers",
        desc: "Dudas operativas de vendedores.",
        area: "Atención",
        date: "08 Dic 2025",
        severity: "BAJO",
        severityClass: "badge--success-light",
        status: "ABIERTO",
        statusClass: "badge--danger-light",
      },
    ],
  },

  {
    id: "nestle",
    nombre: "Nestlé México",
    meta: "Alimentos · Refrigerados",
    nivel: "BAJO",
    tipo: "success",
    otif: "99%",
    puntual: "98%",
    nps: "9/10",
    quejas: "0",
    tendencia: "↑ Operación óptima",
    diagnostico: "diagnostico-Nestle.html",
    since: "2018",
    manager: "Laura Sánchez",

    services: [
      {
        name: "Distribución Refrigerada",
        desc: "Entrega de productos sensibles a temperatura en cadena de frío.",
        area: "Transporte",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "99%",
        slClass: "severity-low text-center",
        nps: "9/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Control Frío",
        desc: "Monitoreo y control de inventario refrigerado en centros logísticos.",
        area: "Almacén",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "99%",
        slClass: "severity-low text-center",
        nps: "9/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Coord. Supply",
        desc: "Planificación logística de abastecimiento y reposición con alta precisión.",
        area: "Coordinación",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "99%",
        slClass: "severity-low text-center",
        nps: "9/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Tracking Avanzado",
        desc: "Seguimiento en tiempo real de unidades y pedidos críticos.",
        area: "Tecnología",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "99%",
        slClass: "severity-low text-center",
        nps: "9/10",
        npsClass: "severity-low text-center",
      },
      {
        name: "Soporte Premium",
        desc: "Atención especializada para incidencias logísticas y ajustes operativos.",
        area: "Atención",
        expected: "01-Dic",
        real: "01-Dic",
        realClass: "severity-low",
        sl: "99%",
        slClass: "severity-low text-center",
        nps: "9/10",
        npsClass: "severity-low text-center",
      },
    ],

    complaints: [],
  },
];


/* =========================================
   DATOS POR ÁREA (DASHBOARD)
   ========================================= */
const areaDatos = {
    transporte: {
        titulo:  "Transporte",
        valor:   88,
        resumen: "Operación por encima del objetivo. Rutas urbanas con leve congestión en horarios pico. 8 unidades con mantenimiento pendiente.",
        kpis: [
            { label: "Puntualidad",      valor: "88%",  meta: "Meta ≥90%",   clase: "warning" },
            { label: "Unidades activas", valor: "142",  meta: "Total: 150",  clase: "" },
            { label: "Incidencias",      valor: "7",    meta: "Límite ≤3",   clase: "danger" },
            { label: "Km prom/ruta",     valor: "312",  meta: "Óptimo ≤280", clase: "warning" }
        ]
    },
    almacen: {
        titulo:  "Almacén",
        valor:   72,
        resumen: "Exactitud de inventario crítica (72%). Tiempo de picking duplica el objetivo. Capacidad al 91% genera cuellos de botella.",
        kpis: [
            { label: "Exactitud inv.",  valor: "72%",   meta: "Meta ≥95%",   clase: "danger" },
            { label: "Tiempo picking",  valor: "38min", meta: "Meta ≤20min",  clase: "danger" },
            { label: "Errores surtido", valor: "14",    meta: "Límite ≤2",   clase: "danger" },
            { label: "Capacidad",       valor: "91%",   meta: "Óptimo ≤85%", clase: "warning" }
        ]
    },
    coordinacion: {
        titulo:  "Coordinación Logística",
        valor:   95,
        resumen: "Operando justo en el límite del SLA (95%). Sin margen ante eventualidades. Reprogramaciones con tendencia al alza.",
        kpis: [
            { label: "Cumpl. SLA",     valor: "95%",   meta: "Meta ≥95%",   clase: "" },
            { label: "Entregas perf.", valor: "93%",   meta: "Meta ≥92%",   clase: "" },
            { label: "Reprog. mes",    valor: "3",     meta: "Límite ≤5",   clase: "" },
            { label: "T. respuesta",   valor: "18min", meta: "Meta ≤20min",  clase: "" }
        ]
    },
    tecnologia: {
        titulo:  "Tecnología y Monitoreo",
        valor:   60,
        resumen: "Uptime crítico en 60%. 22% de la flota sin GPS activo. 22 alertas técnicas abiertas sin responsable asignado.",
        kpis: [
            { label: "Uptime",          valor: "60%",  meta: "Meta ≥99%",  clase: "danger" },
            { label: "Flota con GPS",   valor: "78%",  meta: "Meta ≥95%",  clase: "danger" },
            { label: "Alertas abiertas",valor: "22",   meta: "Límite ≤5",  clase: "danger" },
            { label: "T. resolución",   valor: "4.2h", meta: "Meta ≤1h",   clase: "danger" }
        ]
    },
    cliente: {
        titulo:  "Atención al Cliente",
        valor:   80,
        resumen: "NPS por debajo del objetivo (6.8 vs 8.5). 8 escalaciones abiertas sin cierre. Primera respuesta tarda 2.1h, el doble del estándar.",
        kpis: [
            { label: "NPS",              valor: "6.8",  meta: "Meta ≥8.5",  clase: "warning" },
            { label: "Casos cerr./día",  valor: "12",   meta: "Meta ≥15",   clase: "warning" },
            { label: "Escalaciones",     valor: "8",    meta: "Límite ≤3",  clase: "danger" },
            { label: "T. 1ra respuesta", valor: "2.1h", meta: "Meta ≤1h",   clase: "danger" }
        ]
    }
};